# Generated by Django 5.0.7 on 2026-06-16 13:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='is_current_version',
            field=models.BooleanField(default=True, verbose_name='是否当前版本'),
        ),
        migrations.AddField(
            model_name='license',
            name='original_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_versions', to='licenses.license', verbose_name='原始证照'),
        ),
        migrations.AddField(
            model_name='license',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='版本号'),
        ),
        migrations.AlterField(
            model_name='license',
            name='license_no',
            field=models.CharField(max_length=80, verbose_name='证照编号'),
        ),
        migrations.AlterUniqueTogether(
            name='license',
            unique_together={('license_no', 'version')},
        ),
        migrations.CreateModel(
            name='LicenseRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(max_length=60, verbose_name='申请人')),
                ('applicant_department', models.CharField(max_length=80, verbose_name='申请部门')),
                ('apply_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='申请日期')),
                ('reason', models.TextField(blank=True, verbose_name='续期原因')),
                ('new_issue_date', models.DateField(blank=True, null=True, verbose_name='新发证日期')),
                ('new_expiry_date', models.DateField(blank=True, null=True, verbose_name='新到期日期')),
                ('new_license_no', models.CharField(blank=True, max_length=80, verbose_name='新证照编号')),
                ('status', models.CharField(choices=[('pending', '待提交'), ('reviewing', '审核中'), ('approved', '已批准'), ('in_progress', '续期中'), ('completed', '已完成'), ('rejected', '已拒绝')], default='pending', max_length=32, verbose_name='状态')),
                ('reviewer', models.CharField(blank=True, max_length=60, verbose_name='审核人')),
                ('review_date', models.DateField(blank=True, null=True, verbose_name='审核日期')),
                ('review_comments', models.TextField(blank=True, verbose_name='审核意见')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='完成日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='licenses.license', verbose_name='证照')),
                ('new_license', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewal_record', to='licenses.license', verbose_name='新证照记录')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
